// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0z4jSu0CnAGX8DhcSGYRhtb_yha8jN8A',
    appId: '1:282433385053:web:d3c5853c192cb393e313b4',
    messagingSenderId: '282433385053',
    projectId: 'classtime-edd7a',
    authDomain: 'classtime-edd7a.firebaseapp.com',
    storageBucket: 'classtime-edd7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpW8paz7zZ4wv9F-XuwllR7CDCk9zmSI',
    appId: '1:282433385053:android:c9bb63b942ddcad4e313b4',
    messagingSenderId: '282433385053',
    projectId: 'classtime-edd7a',
    storageBucket: 'classtime-edd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGzlgdUmzZ4aYafWU6LEMvRJ-2VqQrZQI',
    appId: '1:282433385053:ios:2f8b79132c1ac8d7e313b4',
    messagingSenderId: '282433385053',
    projectId: 'classtime-edd7a',
    storageBucket: 'classtime-edd7a.appspot.com',
    iosBundleId: 'com.example.classtimeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGzlgdUmzZ4aYafWU6LEMvRJ-2VqQrZQI',
    appId: '1:282433385053:ios:318f35d39e4993cbe313b4',
    messagingSenderId: '282433385053',
    projectId: 'classtime-edd7a',
    storageBucket: 'classtime-edd7a.appspot.com',
    iosBundleId: 'com.example.classtimeApp.RunnerTests',
  );
}
